site_name: My Docs

nav:
    - Home: index.md
    - Guides:
        - guides/getting-started.md    
    - Setup: setup.md
    - About: about.md
  
theme:
  name: material
  language: bg
  icon:
    logo: material/home
  features:
    - navigation.top
    - navigation.expand
  # font:
  #   text: Roboto
  #   code: Roboto Mono

markdown_extensions:
  - toc:                 
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_name: Github
repo_url: https://github.com/dragomir-d/unit-docs/
edit_uri: 'tree/main/docs'

plugins:
    - search
    - git-revision-date
    - search
    - pdf-export

# extra_css:
#   - stylesheets/extra.css
