site_name: My Docs

nav:
    - Home: index.md
    - Guides:
        - guides/getting-started.md    
    - Setup: setup.md
    - About: about.md
  
theme:
  name: material
  language: bg
  icon:
    logo: material/home
  features:
    - navigation.top
    - navigation.expand

markdown_extensions:  
  - toc:                 
      permalink: true

repo_name: Github
repo_url: https://github.com/dragomir-d/unit-docs/
edit_uri: 'docs/'

plugins:
    - search
    - git-revision-date
    - search
    - pdf-export
